#!/usr/bin/env python
"""Mirror src/datasmith/harbor_adapter into harbor's adapters/formulacode.

    python scripts/sync_harbor_adapter.py --write | --check [--harbor PATH]

Only the renderer modules and template/ are generated; everything else there
(and template/task.toml) is harbor's own and left alone.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "src" / "datasmith" / "harbor_adapter"
RENDER_MODULES = ("adapter.py", "utils.py", "records.py", "stamp.py")
HEADER = "# DO NOT EDIT: generated by datasmith scripts/sync_harbor_adapter.py\n"
NO_HEADER = {"template/instruction.md"}  # rendered verbatim into the agent's prompt
PRESERVED = {"template/task.toml"}


def _template_files(root: Path) -> list[Path]:
    files = (root / "template").rglob("*")
    return sorted(p for p in files if p.is_file() and "__pycache__" not in p.parts and p.suffix not in (".pyc", ".pyo"))


def _render(rel: str, text: str) -> bytes:
    text = re.sub(r"^(\s*)from datasmith\.harbor_adapter\.(\w+) import", r"\1from \2 import", text, flags=re.M)
    if rel not in NO_HEADER:
        lines = text.split("\n")
        keep = 0  # a shebang and a PEP 263 coding line stay on top
        if lines[0].startswith("#!"):
            keep = 2 if len(lines) > 1 and lines[1].startswith("#") and "coding" in lines[1] else 1
        text = "\n".join(lines[:keep]) + ("\n" if keep else "") + HEADER + "\n".join(lines[keep:])
    return text.encode()


def generated_files() -> dict[str, tuple[Path, bytes]]:
    srcs = [SRC / m for m in RENDER_MODULES] + _template_files(SRC)
    return {(rel := s.relative_to(SRC).as_posix()): (s, _render(rel, s.read_text())) for s in srcs}


def _stale(dst: Path, expected: dict) -> list[str]:
    found = {p.relative_to(dst).as_posix() for p in _template_files(dst)}
    return sorted(found - set(expected) - PRESERVED)


def check(dst: Path) -> list[str]:
    expected = generated_files()
    problems = [
        f"{'DIFFERS' if (dst / rel).is_file() else 'MISSING'}  {rel}"
        for rel, (_, data) in expected.items()
        if not (dst / rel).is_file() or (dst / rel).read_bytes() != data
    ]
    return problems + [f"STALE    {rel}" for rel in _stale(dst, expected)]


def write(dst: Path) -> None:
    expected = generated_files()
    for rel, (src, data) in expected.items():
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.is_file() or target.read_bytes() != data:
            target.write_bytes(data)
            print(f"WROTE    {rel}")
        if src.stat().st_mode & 0o100:
            target.chmod(src.stat().st_mode & 0o777)
    for rel in _stale(dst, expected):
        (dst / rel).unlink()
        print(f"REMOVED  {rel}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true", help="exit 1 on any byte drift")
    ap.add_argument("--harbor", type=Path, default=Path(os.environ.get("HARBOR_ROOT", Path.home() / "harbor")))
    args = ap.parse_args(argv)
    if not (args.harbor / "adapters").is_dir():
        print(f"[sync] {args.harbor} is not a harbor checkout (no adapters/)", file=sys.stderr)
        return 2
    dst = args.harbor / "adapters" / "formulacode"
    if args.write:
        write(dst)
    problems = check(dst)
    print("\n".join([*problems, f"[sync] {dst}: {len(problems)} problem(s)"]))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
